### ISSUE TITLE
Expose expected_minimum including standard deviation in the frontend

### ISSUE THREAD

**Issue by rtaaning** [BoostV/process-optimizer-frontend#106]
Expose expected_minimum in the frontend

This issue depends on BoostV/process-optimizer-api#10

**Comment by dk-teknologisk-mon** [comment]
The back-end now supports returning standard deviation with the expected minimum. I would prefer it if we change the way expected minimum is shown, so that the expected score is shown as the range `[mean-2*std to mean+2*std]` instead of just the mean.
