### ISSUE TITLE
Upload of .csv file results in "experiment run fail" with Decimal symbol is set to ","

### ISSUE THREAD

**Issue by rtaaning** [BoostV/process-optimizer-frontend#137]
Upload of .csv file results in "experiment run fail" if windows symstem Decimal symbol is set to "," while the numbers in the .csv file is written with "."
It may be more specific than this, but it appears that not all numbers are interpreted as numbers even if the .csv file only contains number with "." decimal symbol.

**Comment by rtaaning** [comment]
The behaviour originated from a value in the input data that was not within the parameter space defined in the parameter table. 

It could be very useful to have more clear error handling in the front-end. A good first step would be to pass on the error statement from the backend

**Comment by langdal** [comment]
Agreed - tracked in issue #122
