### ISSUE TITLE
Assign meta data to each data point (numbering of experiments)

### ISSUE THREAD

**Issue by langdal** [BoostV/process-optimizer-frontend#138]
Examples of meta data can be:

- an ID associated with each each data point, i.e., each line in the data table.
- a description of the experiment run
- ranking information to be used in future auto generation of scoring functions
- enabled/disabled state

The implementation 
- MUST support CSV import/export.
- MUST be robust when loading data files with missing meta data fields
- SHOULD support new custom fields without breaking old data

One solution for CSV support could be to include all meta data fields as separate columns in the CSV. This will force the meta data format to be only one level deep

**Comment by abbl-DTI** [comment]
Another example is

- Data point enabled/disabled
