### ISSUE TITLE
Migrate API paths to client side logic

### ISSUE THREAD

**Issue by lasseborly** [BoostV/process-optimizer-frontend#150]
We essentially have a server running in form of the API paths just to proxy the http calls and do some data handling.
Therefore we have complexity in the application that does not serve an obvious purpose and is not allowing us to statically host the
frontend.

**Describe the solution you'd like**

We want to migrate the API paths to client side logic instead of the API paths.

**Describe alternatives you've considered**

Alternatively we might have migrated the API path endpoints to separate applications.
This again would prove to be an added complexity which isn't really warranted but would bring the benefit of having the ability to statically host the frontend.

**Comment by lasseborly** [comment]
Do we want to add a milestone to this? @langdal

**Comment by langdal** [comment]
We haven't really used milestones in the project yet. 
Let's discuss using them properly at the next project meeting.
