### ISSUE TITLE
Automatically replace commas with periods in data entry fields

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [BoostV/process-optimizer-frontend#211]
**Is your feature request related to a problem? Please describe.**
An unfortunate side-effect of being based in Denmark is that users frequently use commas as the decimal indicator rather than period (e.g. they write 0,5 and not 0.5). At present, numbers in this format completely bricks the front-end, but the user is not told why nothing works.

**Describe the solution you'd like**
I would like all fields that accept numerical input to automatically convert commas into periods. This would include the min/max fields when defining factors, the "Desired further improvement" setting and all the fields for data entry (factors and score). It appears very unlikely to me that English-based users would ever write commas by mistake (e.g. actually typing out 10000 as 10,000) so I do not forsee any problems with automatic conversion.

**Describe alternatives you've considered**
A different solution would be to provide meaningful error messages, like requested in #122, or to immediately highlight that you should _never_ use a comma in a numerical field.

**Comment by langdal** [comment]
Fixed in #227
