### ISSUE TITLE
The dropzone SVG icon does not apply style in production

### ISSUE THREAD

**Issue by langdal** [BoostV/process-optimizer-frontend#35]
Expected:
![image](https://user-images.githubusercontent.com/558239/117354574-c6a3cc80-aeb1-11eb-9b04-bc26c1d07f86.png)

Actual:
![image](https://user-images.githubusercontent.com/558239/117354406-92301080-aeb1-11eb-921b-8cec55143587.png)

**Comment by j-or** [comment]
Looks like the css is there but is overriden by material-ui. Possible solution: https://material-ui.com/styles/api/#stylesprovider -> injectFirst

**Comment by langdal** [comment]
Adding styles provider does not solve the issue
