### ISSUE TITLE
Too many significant digits when suggesting next experiment

### ISSUE THREAD

**Issue by dk-teknologisk-mon** [BoostV/process-optimizer-frontend#59]
The front end tends to suggest new settings to a silly high number of significant digits (though only for parameters whose upper/lower limits involes a non-integer number?), like shown below:

![image](https://user-images.githubusercontent.com/64902587/117977730-6db0ba00-b331-11eb-8340-5248fd94a7b6.png)

An easy fix would be to round to three significant digits by default, or alternatively 1/1000th of the length of the dimension in question (so if your limits are 0 and 20, you round to the nearest 0.02).

**Comment by langdal** [comment]
Solved in API backend
