### ISSUE TITLE
Enterring floats ending on .0 in the frontend returns integer value to the backend

### ISSUE THREAD

**Issue by rtaaning** [BoostV/process-optimizer-frontend#78]
Enterring float range between 0.0 and 1.0 gives wrong performance on "next experiment", only returning integer values:

![image](https://user-images.githubusercontent.com/38616171/122871662-a334c400-d32f-11eb-9bd4-1dc765aeefe9.png)

Enterring float range between 0.1 and 1.1 gives expected performance on "next experiment":

![image](https://user-images.githubusercontent.com/38616171/122871493-65d03680-d32f-11eb-8d4c-0bebbbcf9bc6.png)

**Comment by dk-teknologisk-mon** [comment]
I would probably suggest that when a solution is implemented, it is done in such a fashion that the user has to specify whether a variable is continuous or discrete, with continuous being the default choice, that gets applied unless you actively do something. It would seem natural to most people to enter min/max values as whole numbers in very many cases, _without_ the implication that they are discrete integers. This is also how this choice is dealt with In classical DOE software, such as Design Expert:
![image](https://user-images.githubusercontent.com/64902587/123417481-1b151f80-d5b8-11eb-95e7-d1d6b48968b9.png)

**Comment by langdal** [comment]
Having looked a bit into the code the proper solution seems to be in line with the suggestion from @dk-teknologisk-mon 
We suggest to add an input type to the "Add variable" dialog like in this mock-up
![image](https://user-images.githubusercontent.com/558239/124082820-6febe680-da4d-11eb-8476-ccbfdc679315.png)
